Attempt to build for osx-arm64
nextstrain/conda-base pull request #80
Opened 2024-07-12 14:09 UTC by corneliusroemer

## Description of proposed changes

## Related issue(s)

## Checklist

- [ ] Checks pass

2024-07-12 19:12 UTC, victorlin commented on .github/workflows/ci.yaml
> +          - macos-14 # arm64
Testing in https://github.com/nextstrain/cli/pull/379. We could also test more directly by addressing this:

https://github.com/nextstrain/conda-base/blob/27041953f25141c8216edb8d3ffbd6ea6e1b2a1e/.github/workflows/ci.yaml#L143

2024-07-12 19:12 UTC, victorlin commented on src/recipe.yaml
> +    # TODO: We should avoid pinning too long, this pin was placed in 2023-12-21
I understand where you're coming from here. Supporting Snakemake 8 will require coordination with existing pathogen repos (e.g. https://github.com/nextstrain/ncov/issues/1114). I think it'd be better to surface as an issue in nextstrain/private, not a comment in this file.

2024-07-12 19:33 UTC, corneliusroemer commented on src/recipe.yaml
> +    # TODO: We should avoid pinning too long, this pin was placed in 2023-12-21
Why not both? It's not an XOR is it 😄 

I feel we are too sticky with snakemake - all the code I maintain already works with v8, just some people don't seem to migrate. I remember last time it was quite an effort and I felt quite alone doing it as no one minds using outdated stuff.

And here again, you made that comment 7 months ago yet nothing happened since then 😛

2024-07-12 19:34 UTC, corneliusroemer commented on .github/workflows/ci.yaml
> +          - macos-14 # arm64
If you know how please do!

2024-07-12 20:31 UTC, victorlin commented on src/recipe.yaml
> +    # TODO: We should avoid pinning too long, this pin was placed in 2023-12-21
I think there's a misunderstanding here... I'm not against updating. My point is that simply adding a note as an unrelated TODO in this PR isn't going to get things moving.

I've created this issue which should be more visible. Feel free to edit: https://github.com/nextstrain/private/issues/120

2024-07-16 00:12 UTC, victorlin commented on .github/workflows/ci.yaml
> +          - macos-14 # arm64
Continuing in #83. It's looking quite complicated so let's not let it block this PR and use other ways to test instead.

2024-07-16 04:56 UTC, victorlin commented on .github/workflows/ci.yaml
> +          - macos-14 # arm64
I tested as a one-off using 5dfbe2f161455398de168fd8cca6fac303a38ea2 (based on this PR branch) and it passed on all the pathogen repos currently listed in CI.

2024-07-16 04:58 UTC, victorlin approved these changes
Looks good pending cleanup of commits or squash+merge on GitHub

2024-07-17 17:33 UTC, tsibley requested changes

2024-07-17 17:33 UTC, tsibley commented on src/recipe.yaml
> +    # - gzip  # [not arm64]
Commenting this out seems like an unacceptable regression to me. There's no guarantee that gzip is ambiently available on all systems that are using our Conda runtime, but gzip is a pretty strong requirement for any of our workflows. The gzip on macOS is also Apple gzip not GNU gzip:

```console
blab@blab-mac ~ % type gzip
gzip is /usr/bin/gzip
blab@blab-mac ~ % gzip --version
Apple gzip 353.100.22
blab@blab-mac ~ % sw_vers
ProductName:	macOS
ProductVersion:	12.6.8
BuildVersion:	21G725
```

so we're opened up to compatibility issues there too.

> We don't seem to support selectors

Please try to figure out why the selector isn't working. It seems like it should be. And if it's not possible for some reason, there are other options, better than omitting gzip, like programmatically tweaking the recipe ourselves for macOS arm64 before build.

Separately, the selector `arm64` will match macOS and Windows arm64 build platforms (but not Linux, which instead uses the alternate selector `aarch64` for the same arch on that OS), [see the docs](https://docs.conda.io/projects/conda-build/en/stable/resources/define-metadata.html#preprocess-selectors). We're not building for Windows, but it would be clearer to me make the selector `not (osx and arm64)` or `not osx or not arm64`.

2024-07-17 17:35 UTC, tsibley commented on src/recipe.yaml
> +    # - gzip  # [not arm64]
> Please try to figure out why the selector isn't working. It seems like it should be.

To answer my own request for you: https://boa-build.readthedocs.io/en/latest/recipe_spec.html#preprocessing-selectors

2024-07-17 17:47 UTC, corneliusroemer commented on src/recipe.yaml
> +    # - gzip  # [not arm64]
```suggestion
    # TODO: Remove selector once gzip is available for arm64
    # i.e. once https://github.com/conda-forge/gzip-feedstock/pull/9 is merged
    - sel(not arm64):
      - gzip
```

Thanks @tsibley - I haven't worked with boa before, that pointer is very useful

I wasn't necessarily suggesting for us to remove gzip for all environments, just a temporary workaround for osx-arm64 to unblock tests here until the PR in the feedstock is merged.

2024-07-17 18:05 UTC, corneliusroemer commented on src/recipe.yaml
> +    # - gzip  # [not arm64]
This works!

2024-07-18 18:12 UTC, corneliusroemer commented
Will take a few minutes for gzip arm64 to become available, rerun later then it should work

2024-07-22 19:11 UTC, corneliusroemer commented
@victorlin
> Looks good pending cleanup of commits or squash+merge on GitHub

I will squash :)

2025-02-03 23:34 UTC, victorlin commented
I'm picking this up since I'd like to run MAFFT natively on my M1 Mac and this would be a proper way to allow that in managed runtimes.

2025-02-05 00:10 UTC, victorlin commented
I've gathered and dropped what seems to be unnecessary changes as 3fc1f0325293d8267214a92cae80af62fb21c301. Changes are minimal now and this is ready for re-review.

2025-02-05 06:30 UTC, tsibley approved these changes
Looks good to me. I pushed two commits as an alternative to the temporary commit (see comment); take it or leave it!

2025-02-05 06:30 UTC, tsibley commented on .github/workflows/ci.yaml
> +          fi
Rather than an awkward commit we have to merge and then revert after the first release, consider the alternative I pushed of f530963adae361cc03a06c5b4a7e4c1c7a4a5fc4 (and optionally 50efd2e10d5c6dda62967014432a570bf69c55dc)? If you disagree they're an improvement, then feel free to drop them.

2025-02-05 17:43 UTC, victorlin commented on .github/workflows/ci.yaml
> +          fi
Thanks, those are great! I'll drop abec4e3ef9120b07177bd009d133949c6b0a2833 and merge.

2025-02-05 18:04 UTC, merged