Surface installation failures with GitHub issues
nextstrain/conda-base pull request #90
Opened 2024-08-01 23:40 UTC by victorlin

## Description of proposed changes

This replace the brittle email notification setup with GitHub issues which should be more visible and actionable.

## Related issue(s)

Closes #84

## Checklist

- [x] ~Checks pass~ not applicable to these changes
- [x] Allow this repo to access org secret `GH_TOKEN_NEXTSTRAIN_BOT_REPO` (only `public_repo` is required for issue management but I figured it'd be ok to use an existing secret that has a superset of permissions)

Testing done on personal fork repo:

- [x] [Installation failure = issue created](https://github.com/victorlin/conda-base/actions/runs/10207235130/job/28241629553#step:3:42)
    - Preview: https://github.com/victorlin/conda-base/issues/6
- [x] [Installation failure with existing open issue = no action](https://github.com/victorlin/conda-base/actions/runs/10207253592/job/28241683355#step:3:42)
- [x] [Installation success with existing open issue = issue closed](https://github.com/victorlin/conda-base/actions/runs/10207270882/job/28241728713#step:3:42)
- [x] [Installation success with no open issue = no action](https://github.com/victorlin/conda-base/actions/runs/10207277576/job/28241748338#step:3:42)
- [x] Other open issues are left untouched: https://github.com/victorlin/conda-base/issues/2

2024-08-02 17:17 UTC, genehack approved these changes

2024-08-02 20:04 UTC, tsibley requested changes

2024-08-02 20:04 UTC, tsibley commented on .github/workflows/installation.yaml
> +          if [ "${{ needs.test.result }}" = "failure" ]; then
_non-blocking_

Generally we prefer `[[ ]]` (and thus `==`) over `[ ]` (and `=`), as the former has less quirky semantics around word splitting and path expansion.

2024-08-06 00:59 UTC, victorlin commented on .github/workflows/installation.yaml
> +            --jq '.[] | select(.title == "${{ env.title }}") | .number')
Thanks for raising this edge case. I've tweaked your suggestion and updated to error on multiple matching issues: 625c48ce53969408fcc4d919104d4348f30ac08f

2024-08-06 01:12 UTC, merged

2024-09-12 22:34 UTC, victorlin commented on .github/workflows/installation.yaml
> +                --body-file "$body_file")
Adding in https://github.com/nextstrain/auspice/pull/1856/commits/e3ed31bdd31e1bb28e27ea5b4b4d7685d46930a5